spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-pctl28ik.sql.tencentcdb.com:21598/sqlfather?useSSL=false
    username: root
    password: Lqz15132932230
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''